from typing import Literal, TypeAlias

from pydantic import BaseModel, Field


class ChatStreamRequest(BaseModel):
    """Client request to start a streamed LLM response."""

    type: Literal["chat"] = "chat"
    request_id: str = Field(min_length=1)
    message: str = Field(min_length=1)


class CancelStreamRequest(BaseModel):
    """Client request to cancel an active streamed response."""

    type: Literal["cancel"] = "cancel"
    request_id: str = Field(min_length=1)


class PingRequest(BaseModel):
    """Client heartbeat request."""

    type: Literal["ping"] = "ping"


ClientWebSocketMessage: TypeAlias = (
    ChatStreamRequest
    | CancelStreamRequest
    | PingRequest
)


class StreamStartedEvent(BaseModel):
    """Sent when the server begins processing a streaming request."""

    type: Literal["started"] = "started"
    request_id: str
    model: str


class StreamChunkEvent(BaseModel):
    """Sent for every text chunk generated by the LLM."""

    type: Literal["chunk"] = "chunk"
    request_id: str
    content: str


class StreamCompletedEvent(BaseModel):
    """Sent after the streamed response finishes successfully."""

    type: Literal["completed"] = "completed"
    request_id: str
    model: str


class StreamCancelledEvent(BaseModel):
    """Sent after an active streaming request is cancelled."""

    type: Literal["cancelled"] = "cancelled"
    request_id: str


class PongEvent(BaseModel):
    """Server heartbeat response."""

    type: Literal["pong"] = "pong"


class StreamErrorEvent(BaseModel):
    """Sent when a streaming request fails."""

    type: Literal["error"] = "error"
    request_id: str
    message: str
    code: str = "stream_error"


ServerWebSocketEvent: TypeAlias = (
    StreamStartedEvent
    | StreamChunkEvent
    | StreamCompletedEvent
    | StreamCancelledEvent
    | PongEvent
    | StreamErrorEvent
)
