apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: POST
      timeInterval: 5s
      prometheusVersion: 3.14.0
      prometheusType: Prometheus

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    editable: false
    version: 1
    jsonData:
      httpMethod: GET
